databases:
  - name: KoyOutkarmBudget
    databaseName: budgetapp_50qs
    user: outkarm

services:
  - type: web
    name: recipe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp_50qs
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
